name: LGPD Compliance Check

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PoC Code
        uses: actions/checkout@v3

      - name: Checkout LGPD LSP Server Code
        uses: actions/checkout@v3
        with:
          repository: denisfreitas999/lgpd-compliance-lsp
          path: lsp-server
          ref: main
          token: ${{ secrets.ACTIONS_CHECKOUT_LSP }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install and Compile LSP Server
        run: |
          cd lsp-server
          npm install
          npm run compile

      - name: Install PoC Dependencies
        run: npm install

      - name: Run LGPD Compliance Analysis
        run: node ./lsp-server/server/out/analyze.js .
